let x = -5;
try{
    let arr = new Array(x);
}
catch (ex){
    console.log('error');
}